### ISSUE TITLE
wrong operations order

### ISSUE THREAD

**Issue by uzadude** [joandre/MCL_spark#8]
Hi,
we're looking into using your implementation, so we have compared your results with the original implementation and found some diffs.
The main problem is you normalize before the first iteration but after that you do:
val M2: IndexedRowMatrix = removeWeakConnections(normalization(inflation(expansion(M1))))

That means that in the next iterations the matrix that goes into the iteration is not stochastic.
the order should be:
val M2: IndexedRowMatrix = normalization(inflation(removeWeakConnections(expansion(M1))))

we have tested it and it really gives the correct results.

did you do that on purpose?

**Comment by joandre** [comment]
Hi,

First, thanks for getting involved in the project.

Indeed, I made a mistake. "Stochasticity" of the matrix is not respected. What I forgot in my implementation was to normalize again after the pruning step : 

val M2: IndexedRowMatrix = normalization(removeWeakConnections(normalization(inflation(expansion(M1))))).

My oversight is due to a computation optimization problem. I thought my implementation was too expensive and I unconsciously missed the last normalization step.

Here was my point: I did not want to prune the matrix before normalization to avoid a strong connection to be removed.

Indeed the way I remove weak connection is based on a fixed value and not on the weight percentage of the connection. So the parameter loses its consistency and its meaning for users except when this function is applied to a matrix with normalized weights.

To conclude I should accept your pull request both to correct the error and also to remove a normalization step. And in order to stay consistent, I should modify my pruning approach, so we delete only connections with a normalize weight inferior to my pruning parameter. I will also add a new test to prevent the matrix not to be stochastic.

Let me know if you are ok with my conclusions.

**Comment by joandre** [comment]
A small question : why did you prune the matrix after expansion and not after inflation ?

**Comment by uzadude** [comment]
Just to make sure:
1. I normalize only at the end - not twice. 
2. Indeed I prune after the expansion - means I delete non-normalized edges.

While I can think of logical reasons to justify it, the more important reason to me is that we'll get the same  exact results as the original author's code which I compare to.

**Comment by uzadude** [comment]
Hi,
Little correction - in the above point #2 - the matrix after expansion is still normalized, because is M is stochastic so is M^k for any k. So it makes perfect sense to prune after expansion.

**Comment by joandre** [comment]
Indeed you are right. I have merged your pull-request.
